### ISSUE TITLE
snow above obsidian roof rendering

### ISSUE THREAD

**Issue by radarthefox** [rfresh2/XaeroPlus#105]
could you make it so snow is also effected by the transparent obsidian roof setting? as it is a big problem on 2b2t
![rtgvfbrf](https://github.com/rfresh2/XaeroPlus/assets/132716990/1c81e17f-779e-492b-9a9d-d49d9acdae84)

**Comment by rfresh2** [comment]
I like the idea!

I'm adding a setting to change the opacity of snow directly on top of obsidian in the next update

**Comment by rfresh2** [comment]
This has now been added https://github.com/rfresh2/XaeroPlus/releases/tag/Fabric-1.20.1-78 (and for all 1.20.x versions)

Before/After:

![2024-01-17_17 00 14](https://github.com/rfresh2/XaeroPlus/assets/89827146/3e6333cc-dd8c-4fcb-a637-b3253bd92331)
![2024-01-17_17 00 31](https://github.com/rfresh2/XaeroPlus/assets/89827146/0f22f37e-ee9a-4875-a2e4-41a824aa2ab6)
