### ISSUE TITLE
receiving a xaeros map crash about 8h into world , after i started new session

### ISSUE THREAD

**Issue by hiimrickross** [rfresh2/XaeroPlus#107]
hi.. so i've ben having no problems playing this modpack (prominence ii classic forge) for like 8 hours now with a bunch of extra mods added... but after my last break, when i went to come back to the game, every time i started it up i would crash with this xaero's map null thing. https://pastebin.com/ypbz5ZXy this is the crashlog but I can't make sense of it.. do I delete the map files?

it seems to be becuse of this mod though: https://www.curseforge.com/minecraft/mc-mods/simply-skills

when i add this mod, i get that xaeromap crash. when i remove it, i can load in again. pufferfish skills is ok.

**Comment by rfresh2** [comment]
Can you share the `latest.log` file with this crash instead of just the crash report file? There's not enough info just in the crash report to figure out what's going on.

>  I can't make sense of it.. do I delete the map files

Definitely don't do that, basically ever

**Comment by hiimrickross** [comment]
i found the solution, it was a problem with Simply Skills + Pufferfish's Skills (latest version). There is a 3 week old issues tracker for SS, saying that SS's latest version is only compatible with 0.10 of PS (which is now up to 0.11 or so). When having that mismatch, the game will crash on load, but it blames Xaeros Map always. But with the correct (old) Pufferfish's Skills 0.10, SS works as normal and loads into the game fine. I guess it is crashing somewhere along the way, but Minecraft is blaming XaerosMap.
