### ISSUE TITLE
[Suggestion] Make waystone waypoints permanent

### ISSUE THREAD

**Issue by adamk33n3r** [rfresh2/XaeroPlus#109]
Making them temporary seems a little weird. I would like the option to keep them all even if I log out.

**Comment by rfresh2** [comment]
I don't think there's any benefit to making them permanent, so I'm not planning on doing this.

Benefits of being temporary:
1. Waystones that are removed can be easily sync'd on reconnects
2. Any bugs or issues in the syncing can be resolved after reconnects
3. Settings like XaeroPlus has for waystones being in their own waypoint set can take effect on reconnects
4. The Waystone waypoints are easily distinguished from player-made waypoints

The only benefit to permanent waypoints I can think of is if you want to remove XaeroPlus after you sync the waystones?

**Comment by adamk33n3r** [comment]
I think I may have misunderstood how the sync worked, I didn't realize it would re-add them on login. I agree with your benefits there, thanks for that!
