### ISSUE TITLE
Use Localization

### ISSUE THREAD

**Issue by ghost** [rfresh2/XaeroPlus#11]
Currently all content of this mod is hard-coded, which is not very friendly to users of other languages. I hope that these content can be converted to use language files, so that users can submit translations easily.
PS: If this is done, I will submit a Simplified Chinese translation.

**Comment by rfresh2** [comment]
thanks for the suggestion

**Comment by rfresh2** [comment]
Completed in https://github.com/rfresh2/XaeroPlus/releases/tag/Forge-1.12.2-126

Language files are located here: https://github.com/rfresh2/XaeroPlus/tree/mainline/src/main/resources/assets/xaeroplus/lang

@mczph If you wish to translate please open a PR or DM me the file(s) on discord :)
