### ISSUE TITLE
添加禁用路径点信标光柱功能

### ISSUE THREAD

**Issue by xingchen-Forever** [rfresh2/XaeroPlus#111]
如题，添加禁用路径点信标光柱功能，我觉得这很碍事，但是我又希望使用xaero的服务器名称存储地图数据功能，因此请求添加此功能（选项菜单禁用路径点信标光柱功能）

**Comment by rfresh2** [comment]
Please submit issues in english using your preferred translator app or website.

This is what Google translate thinks you said:

> As the title says, add the function of disabling the waypoint beacon light beam. I think this is very annoying, but I also want to use the xaero server name to store map data, so I request to add this function (the option menu disables the waypoint beacon light beam function)

You can already disable waypoint beacons at: Minimap Settings -> Waypoint Settings -> Waypoint Beacons -> OFF

![javaw_LNOuruUw5M](https://github.com/rfresh2/XaeroPlus/assets/89827146/ef735699-5f18-4666-88b6-5acf6f114653)

**Comment by xingchen-Forever** [comment]
好的，我之前没有找到这个设置，非常感谢指出，也可能是翻译问题使我误解，总之，感谢您
