### ISSUE TITLE
mod默认配置不更改任何xaero原始行为

### ISSUE THREAD

**Issue by xingchen-Forever** [rfresh2/XaeroPlus#112]
如题，希望mod默认配置不更改任何xaero原始行为，所有的功能都默认关闭，用户自行开启。或者提供一个快捷按钮，点击它，所有的功能都关闭，就好像没有安装xaeroplus一样，因为有时候我面对一些东西，可能会：哎？为什么它变成这样了？我如何修改回去？这是哪个功能？等一连串问题，我更希望完全自己配置选项，如果你愿意添加这个功能，非常感谢！

English（Machine translation is not necessarily accurate）：
As mentioned in the title, I hope that the default configuration of the mod will not change any of the original behavior of Xaero, and all functions will be disabled by default and turned on by the user. Or provide a shortcut button, click on it, and all the functions are turned off, as if xaeroplus was not installed, because sometimes I am faced with something that may: Huh? Why did it become like this? How do I modify it back? Which feature is this? And so on and so forth, I'd prefer to configure the options completely by myself, if you're willing to add this feature, thank you very much!

**Comment by rfresh2** [comment]
the vast majority of XP settings are already off by default, if you have a request to change the default for a specific one or to add a setting for a feature that's fine we can discuss that. 

but i don't really see the need for a button to disable all settings
