### ISSUE TITLE
Crash when entering other mods dimensions.

### ISSUE THREAD

**Issue by ghost** [rfresh2/XaeroPlus#12]
I tested several well-known dimension mods,such as The Aether,The Twilight Forest,The Aurorian.
Interestingly, The Aether only crashes when modifying the dim id(like from 4 to 13).
Crash report:https://mclo.gs/S5iXUrQ
By the way,it seems that this mod doesn't support JAVA j9?

**Comment by rfresh2** [comment]
Try disabling the NewChunks highlighting.

This mod is specifically meant for vanilla-ish servers. Compatibility with modded mc is not guaranteed nor something I'm looking to actively support at the moment.

And yes, this mod currently only supports 1.12.2 using java 8.

**Comment by ghost** [comment]
Thank you,it's fine now.
