### ISSUE TITLE
Lag when jumping

### ISSUE THREAD

**Issue by MagicJinn** [rfresh2/XaeroPlus#13]
Whenever I jump up and down the game's framerate drops to 30-40 (previously 165+). Did some testing and other mods do seem to effect the number, but not by much (example, with 20 mods installed, FPS drops to 25, with 0 (other than fabric api and xaero's map mods) it drops to 60)

Version: 1.20.1
Mods: Tested with and without various mods

https://github.com/rfresh2/XaeroPlus/assets/72989508/ee75e67a-3287-4e9f-a969-bbc43ff17595

**Comment by rfresh2** [comment]
I can't reproduce this and there is nothing in XaeroPlus that does anything on jump events.

**Comment by MagicJinn** [comment]
Personally I think it might be something to do with the map switching between 2 y levels. I didn't properly show it in the video but at 13 seconds in the video the map is briefly visible. Although, if you're unable to reproduce it, that's good I guess.

**Comment by rfresh2** [comment]
If you want to investigate further on your side I recommend using [Spark](https://spark.lucko.me/) or [VisualVM](https://visualvm.github.io/) to capture a profile during the lag.
