### ISSUE TITLE
Idea - change world map directory to a specified folder in a specified disk drive

### ISSUE THREAD

**Issue by Spctre23** [rfresh2/XaeroPlus#131]
it would be nice to be able to change the directory of my world map so i can have it on another disk drive, since my world map folder is huge

**Comment by rfresh2** [comment]
you can use [symlinks](https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) to accomplish this.

That's what i personally use and often recommend to others

if you need more help, discuss in the discord
