### ISSUE TITLE
Xaero's Waypoint problem with Xaero's plus don't swicht between nether and overworld

### ISSUE THREAD

**Issue by Tracas** [rfresh2/XaeroPlus#139]
Hello!
Since I installed Better Minecraft everything was perfect until we went to the nether and here I realized the problem.
For context, we are on a server with BMC 1.20 Forge
We have started making waypoints from here to there and when we went to the nether the waypoints did not match, it showed the ones I had made in the overworld. On top of that, waypoints are not changed automatically. I have searched on Google and the only thing I have found is that the author of the Xaeros96 mod recommends not installing the XaeroPlus-Forge-1.20.1 mod together with the map and mini map of the same author.
Since I had nothing to lose (I have already deleted many waypoints) I removed XaeroPlus from the mods folder and it was perfect.

This message is simply for information, I don't know if there is a way to configure it, but since I removed it it works fine, I don't see anything breaking or anything like that.
I leave you a video of my game so you can see it better
https://youtu.be/uGUPFx4yUbw
Thanks

**Comment by rfresh2** [comment]
check if you have this XP setting enabled 
![javaw_6Ok9RZJsbr](https://github.com/rfresh2/XaeroPlus/assets/89827146/a1acb37a-1faf-4ac6-8714-a4d08abd561a)

To get to this setting open the worldmap, click the gear on the top left, and then click "XaeroPlus WorldMap Settings"

Also in the future it's usually faster and easier to get support in my discord
