### ISSUE TITLE
Update to 1.21 Pls

### ISSUE THREAD

**Issue by taspectjs** [rfresh2/XaeroPlus#140]

**Comment by rfresh2** [comment]
can't update until xaero updates the worldmap and minimap mods

**Comment by taspectjs** [comment]
@rfresh2 I looked around but didn't find a repository of Xaeros, he's not developing it public right?

**Comment by rfresh2** [comment]
correct. and you making issues on github or curseforge is not going to make him or any other dev update any faster, be patient

**Comment by taspectjs** [comment]
I was just asking nicely? And I was looking for his repository and came across you first. Have you ever thought about taking over the project/developing something of your own?
