### ISSUE TITLE
Will it backport support 1.18.2 fabric?

### ISSUE THREAD

**Issue by solarflows** [rfresh2/XaeroPlus#146]
I am playing Minecraft version 1.18.2 and would like to ask the author if there are any plans for forward compatibility with this version?

**Comment by rfresh2** [comment]
sorry but i have no plans to backport to 1.18.2 or any other older version

**Comment by solarflows** [comment]
thank you for your reply,

**Comment by SergenteDonato02** [comment]
a whole year has passed. has anything changed?

and can you close this as not planned?

**Comment by rfresh2** [comment]
this issue has already been closed for a year. 

i've already stated i am not porting to 1.18.2

**Comment by SergenteDonato02** [comment]
at least close this as not planned
