### ISSUE TITLE
Minimap won't render caves (not fair play version)

### ISSUE THREAD

**Issue by Alvin6048** [rfresh2/XaeroPlus#149]
![Screenshot 2024-07-16 094707](https://github.com/user-attachments/assets/ead595c0-8032-4732-b710-26ffaca21c80)

**Comment by rfresh2** [comment]
here's a video showing how to enable cave mode on the minimap.

in the future it is usually quicker and easier to ask questions like this in the discord

https://github.com/user-attachments/assets/8a5bd948-7042-41b3-ade5-00243e1852c9

**Comment by Alvin6048** [comment]
Uh, I seem to not have this?

I've never had this issue so I asked on reddit and was told to report the bug here on the github page. The issue is that I used to just run stock settings when I would download, but now when I downloaded it for a new modpack it bugged like this

**Comment by Alvin6048** [comment]
![image](https://github.com/user-attachments/assets/710f7192-483d-483f-8465-8b625b1e07e8)
![image](https://github.com/user-attachments/assets/989dedc5-ada5-471d-af46-e4c90cc680ea)
![image](https://github.com/user-attachments/assets/17a2d351-de48-4031-b52a-06ab67f7eef1)

I have always downloaded from modrinth and never had an issue like this, currently I'm on 1.20.6 using the modrinth launcher

**Comment by Alvin6048** [comment]
I just went into a new profile with only the minimap mod and the map mod and it's the same thing, I'm going to try downloading from curseforge

**Comment by rfresh2** [comment]
xaeroplus changes the default minimap cave mode setting value to off

but you can easily change that in your modpack by changing it in the xaerominimap.txt config

**Comment by Alvin6048** [comment]
I downloaded from curseforge, the modpack only have the minimap, map and fabrics api. It still does the same and looks the same is in my image, I didn't download xaeroplus and cavemod changed from the map on the bottom left is on layered and auto. what do I do?

**Comment by rfresh2** [comment]
i do not understand what you're asking for

i've already shown you how to view cave mode on the minimap with a video. you also need to be underground for cave mode view to toggle.

the worldmap has a separate toggle as you've already seen which you can change the Y level with the slider on layered

**Comment by Alvin6048** [comment]
I sent pictures showing that my game settings do not look like yours. I'll resend them
![image](https://github.com/user-attachments/assets/b4a03271-abd8-4e51-b170-a955529b9206)
![image](https://github.com/user-attachments/assets/966d4350-ad56-45ed-8332-b80129da18d1)
![image](https://github.com/user-attachments/assets/dc824b5a-efb7-45d9-860e-c247a0c0544d)

This might not be stock settings because I was trying to fix it, but as I said it's the same problem when I go over to a new profile with curseforge's files and not modrinth's, it's the same issue with modrinth's on a new profile and I'm sorta confused because I do like cave mode.

**Comment by rfresh2** [comment]
yes i saw your screenshots of the settings. you have cave mode enabled on the minimap.

its still not clear to me what the problem is.

**Comment by Alvin6048** [comment]
the problem is when I go into caves the issue remains, no y level difference on the mini map as I've said. It stays on the ground level and only shows mobs underground

**Comment by rfresh2** [comment]
i still don't understand can you show a video of what the problem is.

i need you to be clear, specifically what you're expecting and what is actually happening

**Comment by Alvin6048** [comment]
what I am expecting is as any other time using this mod, that the minimap and world map would follow my, the players, y level in order for caves to be seen, I am aware that this can be disabled but it is not. what is seen in this video is stock settings, a new modpack made 5 minutes before and just simply me standing still. I showed all the settings incase if needed and I showed you the enlarged minimap using Z.
I've been using this mod for a long time and I've never had this happen to me
https://github.com/user-attachments/assets/f9729ca2-daf1-4cfa-b6cb-593da2f5e806

**Comment by rfresh2** [comment]
1. you don't have xaeroplus installed in your video
2. cave mode does not show because you have no blocks on top of the player. you dug straight down with path to sky unobstructed

**Comment by Alvin6048** [comment]
1. I never used it before why would I need it now?
2. I'm sorry about that
3. it still doesn't work on my main modpack even with xaeroplus
![image](https://github.com/user-attachments/assets/b3b8ea94-19ab-4b35-a005-c2cba448bde3)

**Comment by rfresh2** [comment]
> I never used it before why would I need it now?

you don't need to use xaeroplus

but you are asking for support from me on the xaeroplus github. i am not the creator of xaero's minimap or worldmap. nor affiliated with him

**Comment by Alvin6048** [comment]
what... why on earth did the reddit guy send me this.

im sorry, I'm going to the main github then ig

**Comment by rfresh2** [comment]
lol i think he only does support via curseforge issues

**Comment by Alvin6048** [comment]
pain, I'm so confused on why's this happening

Sorry for everything, have a great day
