### ISSUE TITLE
mimimap view error when joining a world

### ISSUE THREAD

**Issue by xyxt1c** [rfresh2/XaeroPlus#15]
When joining a world, xaero's minimap view and zoom is broken. One click on the scaling slider in minimap settings fixes it.

![2023-06-30_12 50 47](https://github.com/rfresh2/XaeroPlus/assets/138204417/d499912f-959a-46ea-9ccc-f69ba65f729f)

[system-details.txt](https://github.com/rfresh2/XaeroPlus/files/11915784/system-details.txt)

**Comment by rfresh2** [comment]
does this happen without other mods installed?

**Comment by rfresh2** [comment]
Resolved in [Fabric-1.20.1-7](https://github.com/rfresh2/XaeroPlus/releases/tag/Fabric-1.20.1-7)
