### ISSUE TITLE
[Bug - Config] Waypoint Beacon settings aren't saved

### ISSUE THREAD

**Issue by ShinryuAspect** [rfresh2/XaeroPlus#151]
I've found out that there's no current way of storing the values set for the Beacon settings and anytime I log in a world, it gets reset to default values and I have to manually set them to On and set the minimum distance to my desired value. I've also make sure to be on the correct Xearo's World Map/Minimap versions.

**Comment by rfresh2** [comment]
fixed in https://github.com/rfresh2/XaeroPlus/commit/1d99e5fce1166282760c9b7911b45ae48927e7d8

thanks for reporting

available now from github actions or when 2.20 is published soon
