### ISSUE TITLE
Palette newchunks Issue

### ISSUE THREAD

**Issue by taitan194** [rfresh2/XaeroPlus#152]
When flying around  it generates chunk that become old when you try to load them. Tho with liquid stuff it shows them as new

**Comment by taitan194** [comment]
![image](https://github.com/user-attachments/assets/de88a301-15c4-4d92-8144-77ec642ac228)

**Comment by rfresh2** [comment]
can't fix

servers can generate more chunks than it is sending you. 

this is vanilla behavior, there is a built-in chunk send rate limiter in 1.20.4+. Also can be worsened by you having a lower render distance than the server view distance
