### ISSUE TITLE
nether_cave_fix cannot work properly

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [rfresh2/XaeroPlus#156]
The nether map cannot be drawn properly when the air-entrained ores enabled by the server are confused
Repetition method:
1. Install XaeroPlus and its front mods
2. Access a server that has enabled the ore obfuscator with air
3. Enable nether_cave_fix and enter the nether

<img width="453" alt="javaw_B6FTfM1J7J" src="https://github.com/user-attachments/assets/dfc4e972-7883-4e91-bdaa-328944d26cbb">
<img width="736" alt="javaw_WmQzKbKDaq" src="https://github.com/user-attachments/assets/f49a3a62-0303-4df7-be94-309da85d1e2f">

**Comment by rfresh2** [comment]
the only thing nether cave fix does is change how the base mods interpret the current "Cave Mode", similar to if you set Cave Mode to "Full"

it cannot deobfuscate chunks, it makes no changes to how xaero renders or reads the world
