### ISSUE TITLE
Cant play because XaeroMinimap is on a newer Version

### ISSUE THREAD

**Issue by ErfinderLabyrinth** [rfresh2/XaeroPlus#161]
I use XaeroMinimap Version 24.3.0 and XaeroPlus complained that this is not the 24.2.1 Version

**Comment by ErfinderLabyrinth** [comment]
![Screenshot 2024-08-28 094954](https://github.com/user-attachments/assets/5a51f0da-e144-4e44-b4ec-9a41ab4877e7)

**Comment by rfresh2** [comment]
you need to update XaeroPlus.

Each XaeroPlus version is only compatible with a specific version of Minimap and WorldMap

**Comment by ErfinderLabyrinth** [comment]
> you need to update XaeroPlus.
> 
> Each XaeroPlus version is only compatible with a specific version of Minimap and WorldMap

![Screenshot 2024-08-28 095051](https://github.com/user-attachments/assets/ba098314-1341-4709-b6bf-02e55dce632f)

There is no newer Update of XaeroPlus

**Comment by rfresh2** [comment]
yes there is 
![firefox_Q1UyfUhTO1](https://github.com/user-attachments/assets/911cf2f4-b728-4d4b-b0a1-c24714e7efaf)

https://legacy.curseforge.com/minecraft/mc-mods/xaeroplus/files/all?filter-status=1&filter-game-version=1738749986%3A77784

**Comment by ErfinderLabyrinth** [comment]
My Problem, Curseforge had left the old Version in the mods folder, which was loaded
