### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by euquinox** [rfresh2/XaeroPlus#163]
Hi! A player on my server crashes everytime they go near a sunken city from L_Ender's Cataclysm mod. I checked their logs and it said something about the map and XaeroPlus. I suggested that they turn it off and it worked, they were able to rejoin after they turned off XaeroPlus. Is it the mods conflicting with each other or something else?

[hs_err_pid1350.log](https://github.com/user-attachments/files/16827410/hs_err_pid1350.log)

**Comment by rfresh2** [comment]
try updating XaeroPlus to the latest version (2.22.3)

**Comment by euquinox** [comment]
Just updated the modpack yesterday, it is on the last version

**Comment by rfresh2** [comment]
can you get the player who is crashing to upload their their latest.log of the game session where it is crashing

**Comment by rfresh2** [comment]
the log can be uploaded here https://mclo.gs/ and you can paste the link to this issue

**Comment by euquinox** [comment]
https://mclo.gs/PsamH5I

**Comment by rfresh2** [comment]
that's the same hs_err_pid file

i need the log file: `.minecraft/logs/latest.log`

**Comment by euquinox** [comment]
oh, sorry, my bad
here it is https://mclo.gs/brfH5Wq

**Comment by rfresh2** [comment]
Can you get the user to try this build: https://nightly.link/rfresh2/XaeroPlus/actions/runs/10651897021/XaeroPlus-2.23%2Bforge-1.20.1-WM1.39.0-MM24.3.0.zip

(its a convenience link to [this github action run's](https://github.com/rfresh2/XaeroPlus/actions/runs/10651897021) artifacts so they don't need a github account)

**Comment by euquinox** [comment]
that seems to work
we tried to reproduce the crash but got nothing

**Comment by rfresh2** [comment]
awesome, thanks

as some explanation: Java on ARM CPU's like the Mac M1 has a few issues in how it translates java -> native ARM code

its not the first time i've seen similar issues or had to work around them in weird ways by avoiding certain code sections

anyway, i'm planning on publishing 2.23 within the next day or so

**Comment by rfresh2** [comment]
2.23 is released and published now
