### ISSUE TITLE
Cannot read field "offsetX" because "modelConfig" is null

### ISSUE THREAD

**Issue by DxL-Assassin** [rfresh2/XaeroPlus#164]
Random crash, was working fine until today, not sure what has changed.. Before it crashes, the entire HUD vanishes and then the game freezes.
[crash-2024-09-02_01.17.38-client.txt](https://github.com/user-attachments/files/16832555/crash-2024-09-02_01.17.38-client.txt)

**Comment by rfresh2** [comment]
not caused by XaeroPlus, same crash/issue as https://legacy.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/1488

most likely xaero will publish a fix in the next minimap release

if you want to verify XaeroPlus is not causing it:
1. remove XaeroPlus
2. reproduce the same crash again

**Comment by rfresh2** [comment]
minimap 24.4.0 is now out which should fix this
