### ISSUE TITLE
[CRASH] Game crashes whenever you zoom out more than 0.5x in the world map (FORGE 1.20.1)

### ISSUE THREAD

**Issue by remidu64** [rfresh2/XaeroPlus#165]
https://mclo.gs/z7kfr25

**Comment by rfresh2** [comment]
Try reproducing your crash with XaeroPlus removed

**Comment by remidu64** [comment]
okay

**Comment by remidu64** [comment]
it also crashes, time to try to contact the xaero's worldmap devs

**Comment by remidu64** [comment]
time to try to contact the xaero's worldmap devs

**Comment by rfresh2** [comment]
you can report issues to xaero here: https://legacy.curseforge.com/minecraft/mc-mods/xaeros-world-map/issues

its possible there's another mod you have installed causing incompatibility. You could check if you removed all other mods besides worldmap/minimap and weren't able to reproduce the crash

**Comment by remidu64** [comment]
okay

**Comment by remidu64** [comment]
[after a lot of testing, i concluded that xaero's worldmap seems to have a pretty big incompatibility issue
i identified 6 mods that produce the aforementioned problem and it is version independent](https://legacy.curseforge.com/minecraft/mc-mods/xaeros-world-map/issues/922)

**Comment by rfresh2** [comment]
be sure to test both the cases:
1. Only xaero minimap + worldmap installed
2. xaero minimap + worldmap + ONE mod you suspect

Step 2 needs to be done one by one individually for each mod you are testing for compat issues.
But the log you linked indicates you have many mods installed

**Comment by rfresh2** [comment]
resolving this here as its being handled on xaero's side
