### ISSUE TITLE
Some colors of beacon beams does not match the color of the waypoints

### ISSUE THREAD

**Issue by Realzhazha** [rfresh2/XaeroPlus#168]
## Issue

Some colors seem to be swapped
(I am not sure about the right color of dark purple and light purple)
![image](https://github.com/user-attachments/assets/128b8304-48e2-43ac-8ef8-512c6643693d)

## Versions

- Minecraft: 1.20.4
- Xaero's World Map: 1.39.0
- Xaero's Minimap: 24.4.0
- XaeroPlus: 2.23.2

**Comment by rfresh2** [comment]
thanks looks like the green/blue color components got swapped accidentally

will be fixed in next release

**Comment by rfresh2** [comment]
fixed in 2.24 https://github.com/rfresh2/XaeroPlus/releases/tag/2.24
