### ISSUE TITLE
[Feature request] World border

### ISSUE THREAD

**Issue by jakaco** [rfresh2/XaeroPlus#174]
Would it be possible to show the world border on the minimap, as in where it is and when its decreasing in size

**Comment by rfresh2** [comment]
i can render solid colored chunk highlights (see existing chunk highlight features) 

or a rectangular box outline (see render distance feature)

which do you think would work best for the world border?

**Comment by jakaco** [comment]
i feel like the render distance feature would work better tbh

**Comment by rfresh2** [comment]
in 2.24.4 https://github.com/rfresh2/XaeroPlus/releases/tag/2.24.4
