### ISSUE TITLE
[Feature Request] Tie in Baritone into the map interface.

### ISSUE THREAD

**Issue by strunberg** [rfresh2/XaeroPlus#175]
It would be nice if we can right click on the map and tell baritone to walk to a location, or walk use the waypoints to walk to a location instead of teleport.

**Comment by rfresh2** [comment]
already exists in XaeroPlus if you have baritone installed

make sure you have baritone "unoptimized" or "api" - "standalone" will not work.

**Comment by strunberg** [comment]
What Baritone version are you using for 1.21.1? 
"<html>Mod 'Baritone' (baritone) 1.10.2 requires version 1.20.3 or version 1.20.4 of 'Minecraft' (minecraft), but only the<br>wrong version is present: 1.21.1!</html>"

**Comment by rfresh2** [comment]
there is no official release of baritone for 1.21.1

you can either:
1. Compile it yourself from source: https://github.com/cabaletta/baritone/tree/1.21.1
2. Download it from baritone's github actions artifacts: https://github.com/cabaletta/baritone/actions/runs/11355719493
3. Get someone you trust to compile it and give it to you

**Comment by strunberg** [comment]
I ended up downgrading to 1.20.4 
![cxvcxvcxvcxv](https://github.com/user-attachments/assets/bb89cfe6-68d5-4a9e-bb61-e398e49e1afa)
