### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by IdkWhatNameThingyToPut** [rfresh2/XaeroPlus#179]
This happened on modded minecraft 1.12.2 and the issue is that my server crashes on startup when this mod is installed

Crashlog:
[crash-2024-11-05_18.18.02-server.txt](https://github.com/user-attachments/files/17637457/crash-2024-11-05_18.18.02-server.txt)

Latest.log
[latest (4).log](https://github.com/user-attachments/files/17637465/latest.4.log)

I also want to ask while I'm doing this post because I'm not sure if this is a bug linked to this issue or not but how do you access the "Minimap FPS Limiter" settings because I can't seem to find them at all (this feature on this video that I think I found from your mod page https://www.youtube.com/watch?v=hIG-VyGQLao) and also what are the config files for XaeroPlus called?

**Comment by rfresh2** [comment]
installing xaeroplus on servers is not supported. i will try to force disable it in next release

> how do you access the "Minimap FPS Limiter" settings

Only in XaeroPLus for 1.19+

1.12.2 support is on maintenance mode and does not receive new features

**Comment by rfresh2** [comment]
> what are the config files for XaeroPlus called

on 1.12.2 the settings are at the bottom of the default xaero worldmap and minimap config files

`config/xaerominimap.txt` and `config/xaeroworldmap.txt`

and in 1.19+ xaeroplus has its own config file `config/xaeroplus.txt`

**Comment by IdkWhatNameThingyToPut** [comment]
> installing xaeroplus on servers is not supported. i will try to force disable it in next release
> 
> > how do you access the "Minimap FPS Limiter" settings
> 
> Only in XaeroPLus for 1.19+
> 
> 1.12.2 support is on maintenance mode and does not receive new features

Ah ok so I'm guessing there's no plans for you to bring any of the features to the 1.12.2 version at all? It would be really nice if you could atleast put the "Minimap FPS Limiter" stuff on the 1.12.2 version because it seems to be really important performance-wise , if you don't want to/can't then I understand however I might ask some authors of performance mods to include their own type/implementation of something like that in their own mods if that's possible and stuff.

**Comment by rfresh2** [comment]
Yeah I have no plans to backport it. The entire minecraft rendering system is very different on 1.12 so it would not be very simple to do. I don't know if its even possible in the same way.

But if someone wishes to contribute a backport or reimplement it in their own mod both are fine with me.

**Comment by IdkWhatNameThingyToPut** [comment]
Awesome thanks.

**Comment by IdkWhatNameThingyToPut** [comment]
Turns out the StellerCore performance mod for modded minecraft 1.12.2 does something like the "Minimap FPS Limiter" and it works really well. https://github.com/NovaEngineering-Source/StellarCore/issues/23

Can I ask if you ever did anything to stop the minimap from rotating? Is there settings for it in your mod? I feel like a really low FPS limit is probably fine if the map could be stopped from rotating as it seems be the main thing that's probably causing like heaps of choppiness that people could see. If it was static and didn't move people probably wouldn't notice much choppiness at all.

**Comment by rfresh2** [comment]
there's already a setting in the minimap view settings to force north lock up.

**Comment by IdkWhatNameThingyToPut** [comment]
> there's already a setting in the minimap view settings to force north lock up.

Oh wow that's good then thanks, I just tested it with the lock minimap north feature in xaero's minimap and it seems a lot better now like this I didn't notice the choppiness as much since it's not rotating and stuff. Thanks for everything you can close this if you want. Good luck with everything.
