### ISSUE TITLE
Always using the DIM0 directory

### ISSUE THREAD

**Issue by davepusey** [rfresh2/XaeroPlus#29]
Appears to be always using the DIM0 directory, regardless of what "[XP] null OW Dim Dir" is actually set to.

Using:

XaerosWorldMap_1.30.6_Fabric_1.20.jar
Xaeros_Minimap_23.5.0_Fabric_1.20.jar
XaeroPlus-Fabric-1.20.1-13-WM1.30.6-MM23.5.0.jar

on Minecraft 1.20.1 / Fabric 0.14.21

**Comment by rfresh2** [comment]
Resolved in:
* Fabric 1.20.1: https://github.com/rfresh2/XaeroPlus/commit/4d5f914e7b06ac382462c02fc129ec23c3b6c8d9
* Forge 1.20.1: https://github.com/rfresh2/XaeroPlus/commit/a4a32ef458450c268ad2037cc5061de7b764ea8b

thanks for reporting!
