### ISSUE TITLE
Line break doesn't work

### ISSUE THREAD

**Issue by ZHAY10086** [rfresh2/XaeroPlus#31]
The `\\n` doesn't seem to work in tooltips.
![图片](https://github.com/rfresh2/XaeroPlus/assets/34602681/3da9a17c-455b-4aa8-a26a-1887df8c14ec)

**Comment by rfresh2** [comment]
Fixed in https://github.com/rfresh2/XaeroPlus/commit/7f844c0f1ae51a371d0c8f43dc6edd7bee4a4b2d

thanks for reporting!
