### ISSUE TITLE
Interdimensional teleportation support

### ISSUE THREAD

**Issue by ghost** [rfresh2/XaeroPlus#32]
Vanilla xaero can teleport when the cheat mode is turned on, but it does not support interdimensionality. For example, it is impossible for you to teleport from the overworld world to the nether.And this feature is really important for both vanilla and modded players because it saves a lot of time.
.
Hope to get this function in this addon, of course, if it is not easy to implement or it doesn't support other mods dimensions,just ignore this issue

PS:the new feature `Waystones integration` does it mean I don't need to install [w2w](https://www.curseforge.com/minecraft/mc-mods/waystones2waypoints)

**Comment by rfresh2** [comment]
Thanks for the suggestion. I don't think it'll be very difficult actually - at least for the vanilla dimensions. I believe it will require `execute` command permissions though

> PS:the new feature Waystones integration does it mean I don't need to install [w2w](https://www.curseforge.com/minecraft/mc-mods/waystones2waypoints)

Yes, or you can disable XaeroPlus's version and use that one. Whichever you prefer. As far as features I think the main one is XaeroPlus will also remove waypoints for waystones that are removed in the world.

**Comment by rfresh2** [comment]
Actually it seems like minecraft only added command support for that in 1.13+. So it would only be possible in the 1.20+ versions of XaeroPlus.

It might be possible in 1.12 but it would require a server mod and XaeroPlus is only client-side.

**Comment by ghost** [comment]
@rfresh2 
It looks like xaero is teleporting through commands and I think forge actually has a similar command.

/forge setdimension playername dimid x y z

Is that helpful?

**Comment by rfresh2** [comment]
Yeah that's perfect. 

Completed in https://github.com/rfresh2/XaeroPlus/commit/83b30ae94dc52500fe4784a430b986012f83f551

reopen if it doesn't work :)

**Comment by ghost** [comment]
@rfresh2 it doesn't work.But I don't have permission to reopen.

**Comment by rfresh2** [comment]
can you describe what you're doing and what is not working?

**Comment by ghost** [comment]
In the waypoint gui, waypoints in other dimensions are displayed as untransportable. And when switching dimensions in the WorldMap, there is no response after clicking Teleport.

**Comment by rfresh2** [comment]
ok, i see its on the waypoints GUI. i only added support on the WorldMap GUI. i'll see if i can get the waypoints to work similarly

**Comment by rfresh2** [comment]
https://github.com/rfresh2/XaeroPlus/commit/a651391756f1a2f93473e89a32782cf90ed4253b this should add support for waypoints GUI cross-dimension teleports.

also i added a setting to place waystones into waypoint corresponding to their dimension.  https://github.com/rfresh2/XaeroPlus/commit/749461e2f5b0c18669679d3ba239bcfc7aa25f9c Due to awkwardness in how xaero handles waypoint sets this might cause issues in certain cases. But for standard use it seems to work ok for me.

**Comment by ghost** [comment]
@rfresh2 After testing, the function can be used normally, thank you very much. Also please help me add these lines to zh_cn.lang

```
setting.world_map.cross_dim_waystones_sync=传送石碑维度同步
setting.world_map.cross_dim_waystones_sync.tooltip=将传送石碑同步到根据其维度设置的（默认）路径点
setting.world_map.cross_dimension_teleport=跨维度传送
setting.world_map.cross_dimension_teleport.tooltip=如果 XaeroPlus 维度被切换，同时修改传送到该维度的命令
```

**Comment by rfresh2** [comment]
done https://github.com/rfresh2/XaeroPlus/commit/4d0b713588bb8bc044bd6af2a415073dd7e198f2
