### ISSUE TITLE
The New Xaero`s Minimap and WorldMap Update is out. Please Update your mod for all your Versions from 1.12.2 and 1.20+

### ISSUE THREAD

**Issue by Titoo8899** [rfresh2/XaeroPlus#34]
I hope the Update of your mod with the Compatible to the newest Versions comes in next time out.
New Versions Numbers of the Mods:

Forge 1.12.2:
Xaeros_Minimap_23.6.0_Forge_1.12
XaerosWorldMap_1.31.0_Forge_1.12

Forge 1.20+:
Xaeros_Minimap_23.6.0_Forge_1.20
XaerosWorldMap_1.31.0_Forge_1.20

Fabric 1.20+:
Xaeros_Minimap_23.6.0_Fabric_1.20
XaerosWorldMap_1.31.0_Fabric_1.20

**Comment by rfresh2** [comment]
Yes i'm already aware. I have a bot notify me in discord. Not necessary to create github issues the instant updates are released.
