### ISSUE TITLE
Waypoint Screen is in Fullscreen to wide on the left and right side of the screen

### ISSUE THREAD

**Issue by Titoo8899** [rfresh2/XaeroPlus#38]
Hi,
I hope you can a fix for this Problem make. The Screen of who all Waypoints was safe and create was in Fullscreen to wide on the left and right side of the Screen and we can the Searchbar etc. no see.

![2023-08-01_19 05 21](https://github.com/rfresh2/XaeroPlus/assets/42325138/4f6e1f6d-5a4c-40f9-82e7-365fc31e6afa)

**Comment by rfresh2** [comment]
What is your

1. screen resolution?
2. screen size?
3. GUI scaling setting set to? (In Minecraft settings)

**Comment by Titoo8899** [comment]
1: screen resolution - 1920 X 1080
2: screen size - I have a "HP 24o" = 24 Zoll (inch) (60,96 cm)
3: GUI Scaling Setting - AUTO

**Comment by rfresh2** [comment]
Set your GUI scale to "Normal" (or "Large")

**Comment by Titoo8899** [comment]
okay I will test it
