### ISSUE TITLE
Baritone right click options are broken when Prefer overworld waypoints is on 

### ISSUE THREAD

**Issue by gargamelius** [rfresh2/XaeroPlus#39]
When the setting "Prefer overworld waypoints" is turned on and you try to use the baritone right click goal thingy in the nether you end up at 8x the coordss that you wanted to go to

Video showcasing the issue -> https://www.youtube.com/watch?v=6ZhgYIO6J6w

**Comment by rfresh2** [comment]
As a workaround you can right click next to the waypoint and create a baritone goal, and then it should path you to the nether coords.

**Comment by rfresh2** [comment]
Resolved in https://github.com/rfresh2/XaeroPlus/releases/tag/Forge-1.12.2-142

will port to 1.20 versions later

**Comment by gargamelius** [comment]
I love you <3

**Comment by rfresh2** [comment]
Forge 1.20: https://github.com/rfresh2/XaeroPlus/releases/tag/Forge-1.20.1-21

Fabric 1.20: https://github.com/rfresh2/XaeroPlus/releases/tag/Fabric-1.20.1-34
