### ISSUE TITLE
[1.20.1] [XWM 1.32.0 - XMM 23.6.1] Breaking Waypoint Manager

### ISSUE THREAD

**Issue by Dragnier** [rfresh2/XaeroPlus#41]
Your mod is making the waypoint manager treat everything as the overworld instead of making separate dimension waypoint sets automatically. This breaks the teleport functionality of the waypoints (OP/Creative) and can makes unnecessary clutter of waypoints by showing all of them all the time in world instead of just the ones for the current dimension.

The way it breaks the teleport is sending you to the specified coordinates in whatever dimension you are in instead of actually switching your dimension... which can put you inside blocks or even in the void depending on where you are.

**Comment by rfresh2** [comment]
You can disable the "Prefer Overworld Waypoints" setting to restore the original behavior.

This setting only affects OW and nether waypoints so you still get waypoints for other dimensions like the end even with it on.

The reason I have this setting and behavior is that there's an inherent tradeoff with multiple waypoint sets - you can't view both overworld and nether waypoint sets at the same time - at least without doing a bunch of clicking in menu's every time you switch dimensions. But yeah the flipside is teleporting to a nether waypoint wouldn't retain the metadata that it is in the nether.

**Comment by Dragnier** [comment]
If it is an intended feature with a toggle config option which breaks default functionality of the original mod on purpose, it should probably be off by default. Just my two cents.

**Comment by rfresh2** [comment]
I set the default to false now in the 1.20 versions:

Forge 1.20.1: https://github.com/rfresh2/XaeroPlus/commit/41998bc6b0ee665dd5a3f24d99ae6b2896548333

Fabric 1.20.1: https://github.com/rfresh2/XaeroPlus/commit/f5a37bc7480279813644f85d219a94e50f5c337c

1.12 its going to remain defaulted to on as 1.12 is mostly used by anarchy players where the feature is most useful.
