### ISSUE TITLE
FPS Stutter on Cave Layer Change

### ISSUE THREAD

**Issue by rfresh2** [rfresh2/XaeroPlus#42]
Seems to occur while changing cave layers.

Profiles during switching cave layers quickly:

* With XaeroPlus: https://spark.lucko.me/22VqWRTckT
* Without XaeroPlus: https://spark.lucko.me/89kxvD4AWX

Original issue on BetterMC: https://github.com/LunaPixelStudios/Better-MC/issues/1342

todo: 
* Check if related to minimap scaling
* Check locks on regions causing waits
* Check if related to Fast Mapping

**Comment by rfresh2** [comment]
Seems to be related to Fast Mapping, can be mitigated by reducing the chunk write rate limit or turning fast mapping off.

I'm going to investigate the processing if the processing on the tick event can be done in an async thread. If not, then will reduce the default rate limit setting value.

**Comment by rfresh2** [comment]
Resolved in:

Forge 1.20.1: https://github.com/rfresh2/XaeroPlus/commit/25f63be15bafaa30850e117a8b3e476d803a0880

Fabric 1.20.1: https://github.com/rfresh2/XaeroPlus/commit/c47f79cb34b0729e61e3bf353248faddd3dbfc96

Removed fast mapping of cave layers as these seem to be the main culprit for processing time. I've also reduced the default fast mapping chunk rate limit from 80 to 20.

@chorbintime if you want maximum FPS you can try turning Fast Mapping off in your pack via config. Xaero's default writer is a bit slow and runs on every render tick - but its more heavily rate limited, so ymmv

I would like to get all the map writing off the tick and render events and onto a separate thread. But that's going to require a lot more changes and testing that I'll put off for another day:tm:

**Comment by chorbintime** [comment]
Thank you for the solution & the quick response!
