### ISSUE TITLE
[1.20.1] Crashes when installed with PartyAddon

### ISSUE THREAD

**Issue by DeshiDesu** [rfresh2/XaeroPlus#43]
Mods Installed:
![image](https://github.com/rfresh2/XaeroPlus/assets/120287925/2652e988-09a7-4be0-9262-5d86daa27f65)

Crash report:
The client crashes on startup.
[crash-2023-08-09_20.13.16-client.txt](https://github.com/rfresh2/XaeroPlus/files/12307699/crash-2023-08-09_20.13.16-client.txt)

![image](https://github.com/rfresh2/XaeroPlus/assets/120287925/f5d00e0d-5851-4c2c-9bb0-64ac435111db)
Something about this here ^^^

**Comment by rfresh2** [comment]
There are a lot of changes XaeroPlus makes to both WorldMap and Minimap that basically require no other mod to also try to change.

I'm going to mark this as won't fix as I don't see a way to have to both work without compromises. Sorry.
