### ISSUE TITLE
1.20.1 Server crashes at startup when using newest XaeroPlus

### ISSUE THREAD

**Issue by markaabo** [rfresh2/XaeroPlus#44]
Hello, as the title says the newest version of the mod seems to work perfectly when doing singleplayer but when its installed on a server the server crashes at start up.

I have attached the logs from the server
[debug.log](https://github.com/rfresh2/XaeroPlus/files/12321335/debug.log)
[latest.log](https://github.com/rfresh2/XaeroPlus/files/12321336/latest.log)

Edit, after testing all versions back to "XaeroPlus-Forge-1.20.1-7-WM1.30.6-MM23.5.0" i cannot get ANY version above that one to work at all, it crashes with any never version above 1.20.1-7

**Comment by rfresh2** [comment]
Don't install it on a server, its client side only.

I'll see if I can find a way to make it not crash the server though

**Comment by markaabo** [comment]
> Don't install it on a server, its client side only.
> 
> I'll see if I can find a way to make it not crash the server though

I know, its just when not on the server it says that the server doesn't have the correct mods on it which is annoying to tell the users of the server and explain :P, and thank you :)

**Comment by rfresh2** [comment]
Resolved in https://github.com/rfresh2/XaeroPlus/commit/956cf5de53ca9e0246f67b65e54ddbfcbe9f62a8
