### ISSUE TITLE
[Suggestion] Add Desmos to Xaero waypoint conversion.

### ISSUE THREAD

**Issue by AquaMinerale2b2t** [rfresh2/XaeroPlus#5]
It would be great to be able to convert Desmos.com points into Xaero waypoints.

**Comment by rfresh2** [comment]
Outside the scope of the XaeroPlus mod. Belongs in a separate repo and script similar to 2b2t atlas waypoints import. 

I don't think Desmos has a public API or file you can export anyway so I don't plan on completing this.
