### ISSUE TITLE
[Feature request] Only Worldmap to be required

### ISSUE THREAD

**Issue by Zorklis** [rfresh2/XaeroPlus#50]
So currently XaeroPlus mod crashes when Minimap is missing, but I only want XP for [Fast map region writes](https://cdn.discordapp.com/attachments/963821382569979904/1049947847467995196/Temurin-1.8.0_345_2022.12.06_-_22.44.28.05.DVR.mp4).

**Comment by rfresh2** [comment]
I will not remove the Xaero's minimap dependency, sorry.

You can disable the minimap from being rendered in Minimap settings though.
