### ISSUE TITLE
Does not work with BetterPVP as stated on modrinth

### ISSUE THREAD

**Issue by Zaroz** [rfresh2/XaeroPlus#51]
I am running Minecraft 1.20.1 with the latest stable Fabric release (0.14.22). The game window appears briefly, then crashes before even showing anything.
Here is the ouput log:
https://paste.atlauncher.com/view/e4f3589f-c04b-4944-8d2e-05b8d54835e3

and here is the crash report:
[crash-2023-08-24_14.20.16-client.txt](https://github.com/rfresh2/XaeroPlus/files/12432740/crash-2023-08-24_14.20.16-client.txt)

**Comment by rfresh2** [comment]
You need to update BetterPVP to 23.6.3
