### ISSUE TITLE
Fabric 1.19.4

### ISSUE THREAD

**Issue by t1m013y** [rfresh2/XaeroPlus#52]
Please make fabric 1.19.4 version. I am playing on server with this version.

**Comment by skdii** [comment]
use via fabric

**Comment by t1m013y** [comment]
I can't use 1.12 version and 1.20 version is incompatible. I can't use forge because I have mods that can be installed only in fabric.

**Comment by rfresh2** [comment]
I'm not going to make a 1.19.4 version.

Install this mod: https://www.curseforge.com/minecraft/mc-mods/viafabricplus

you can connect to pretty much any version of MC server from a 1.20.1 client

**Comment by t1m013y** [comment]
> Install this mod: https://www.curseforge.com/minecraft/mc-mods/viafabricplus
> 
> you can connect to pretty much any version of MC server from a 1.20.1 client

Thank you! It works!
