### ISSUE TITLE
Integration with baritone without cheat client on 1.20.1 is not possible?

### ISSUE THREAD

**Issue by krazeral** [rfresh2/XaeroPlus#53]
I didn't find any baritone interactions in the map.

**Comment by rfresh2** [comment]
You need any baritone release installed for 1.20.1 - except the "standalone" version which will not work.

https://github.com/cabaletta/baritone/releases/tag/v1.10.1

**Comment by krazeral** [comment]
Thanks, everything works now. I had the standalone version before. Amazingly fast response time.

**Comment by krazeral** [comment]
Closed.
