### ISSUE TITLE
Baritone Elytra Goal Waypoint Sync

### ISSUE THREAD

**Issue by natopotato390** [rfresh2/XaeroPlus#54]
Fantastic mod!
Using the new elytra baritone beta with XaeroPlus makes nether travel a breeze. 

I don't know if this is intended or not, but when using "*Baritone Elytra Here*", 
or setting goal while using elytra, **the baritone goal is not synced as a temporary waypoint.**

Fixing this would definitely be a nice feature for elytra travel.

**Comment by rfresh2** [comment]
Added in:
https://github.com/rfresh2/XaeroPlus/releases/tag/Fabric-1.20.1-45
https://github.com/rfresh2/XaeroPlus/releases/tag/Forge-1.20.1-32
