### ISSUE TITLE
Log Spam with Vanilla IceCream Fix

### ISSUE THREAD

**Issue by HowardZHY** [rfresh2/XaeroPlus#63]
The detection of Xareo's mods versions should be improved, please use ">=" with versions.
[latest.log](https://github.com/rfresh2/XaeroPlus/files/12702409/latest.log)

**Comment by rfresh2** [comment]
> please use ">=" with versions.

No. XaeroPlus is [explicitly only compatible](https://github.com/rfresh2/XaeroPlus#xaero-versions) with a single WorldMap and Minimap version pair per release.

Failing the version check is supposed to crash your game. If this ice cream mod wants to try to prevent the crash, log spam is the least of your problems. I don't see this as something I can or should improve.
