### ISSUE TITLE
[Suggestion] Add extrapolate option on the map

### ISSUE THREAD

**Issue by IceTank** [rfresh2/XaeroPlus#7]
When you play on 2b you might need to extrapolate lines if you want to follow a perfectly strait line.

Usage could be something like this:
1. Set on point on your map
2. Set another point on your map
3. The map automatically extrapolates the line out and places a new waypoint in line with the two set waypoints. The distance might be configurable or the extrapolated line might display on the map.

**Comment by rfresh2** [comment]
I don't really get the utility of this, can you give an example of when this would be useful?

**Comment by Zarepheth** [comment]
I often want to do that to find strongholds when my selection of mods does not include a compass for that purpose.

Specifically, I stand in one location, mark it with a waypoint. Then I use an ender eye to point me toward the nearest stronghold. I remain facing in the direction where it popped before either falling to the ground or disappearing. Then return the map, zoom out and put another waypoint near the point of the arrow representing me and the direction I'm facing. At that point, it would be very helpful to extend a straight line. Then I travel some distance at ~45-degree angle and repeat. If I could extend both line until they meet, I'd have a good estimate of where to find that stronghold.

It doesn't even have to be an in-world waypoint, just a set of tools on the map to assist with triangulating the location of distant structures and biomes. Once we locate where the lines cross we can use Xaero's waypoint feature to mark it.
