### ISSUE TITLE
[FEATURE] Always use the same color for waystones

### ISSUE THREAD

**Issue by nco2k** [rfresh2/XaeroPlus#70]
it would be cool if we could get an option to always use the same (predefined) color for waystones.

**Comment by rfresh2** [comment]
Are you asking to use the same color for ALL waystones or some way to color each one individually?

**Comment by nco2k** [comment]
my bad, i should have explained it better. when you activate an undiscovered waystone, a new waypoint will be created on the map. the color of the newly created waypoint will be random. sometimes its dark red, sometimes its dark green etc. and im not a fan of that. i wish every waystone waypoint would always get the same color, so that i know immediately when looking at the map, that the waypoint is a waystone, and not a marker that i put down myself.

**Comment by rfresh2** [comment]
Added in https://github.com/rfresh2/XaeroPlus/commit/64d58c31821414cd9fccb864b2894bf513db2ab3

Releases will be auto-built and published shortly
