### ISSUE TITLE
Xaero worldmap 1.35 support

### ISSUE THREAD

**Issue by yavko** [rfresh2/XaeroPlus#71]
There is a new version, and the mod has a dependency on a specific version, so the game can't start.
![image](https://github.com/rfresh2/XaeroPlus/assets/15178513/21ef35b5-e7bf-451f-8bdc-76be6f77613e)

**Comment by rfresh2** [comment]
The new version was released only a few hours ago, I'm working on it. 

In the future please don't create issues for things like this, I already get pinged in the discord.

**Comment by yavko** [comment]
> In the future please don't create issues for things like this, I already get pinged in the discord.

Sorry, didn't know this repository had such a policy. Plus, I'm not in the discord, so I can't see if you are being pinged.
