### ISSUE TITLE
[FEATURE] Dont show "(unset)" when there is no keybinding

### ISSUE THREAD

**Issue by nco2k** [rfresh2/XaeroPlus#76]
if you dont have a keybinding for opening the settings for example, and then right click on the world map or hover over the gear icon with the cursor, it will show "(unset) Open Settings". imho it would look a lot nicer to simply show "Open Settings" without the ugly "(unset)" prefix.

**Comment by rfresh2** [comment]
This has been added in the latest release

**Comment by nco2k** [comment]
thank you for implementing this. it looks a lot cleaner now. i found a small issue however, with the controls tooltip text: https://i.imgur.com/5DIbtBS.jpg

for this section it would probably be best to simply remove the whole line if there is no keybinding.

**Comment by rfresh2** [comment]
It'd better for you to ask Xaero to implement that, the tooltip text is defined in his lang translations. I'd also prefer to not have to write mixins on his mod to implement the original change to begin with

**Comment by nco2k** [comment]
i see. i already asked, but he doesnt want to change it. i take it you also wouldnt be able to exclude the controls tooltip text from this change, so that it still shows the "(unset)" prefix?

**Comment by rfresh2** [comment]
Not without overriding his lang files, which I'd prefer not to do. I don't support nearly as many languages as the base mods
