### ISSUE TITLE
Game crash when turn on Portal chunk highlight and go to other mod's portal based dimension

### ISSUE THREAD

**Issue by nickbanana** [rfresh2/XaeroPlus#77]
As Title describe, when turning on portal chunk highlight and go to other mod's dimension via their respective portal will causing crash.

 Caused by: java.lang.RuntimeException: Unknown dimension: ResourceKey[minecraft:dimension / aether:the_aether]

Mainly reason is the dimension doesn't recognize by mod

minecraft version is 1.20.1, mod version need to verify cause I'm playing on Modpack: Better MC V17

[https://mclo.gs/13cbLs1](https://mclo.gs/13cbLs1)

**Comment by rfresh2** [comment]
This has already been fixed in the latest XaeroPlus versions

**Comment by rfresh2** [comment]
I'll also note that although the crash was fixed, the portal highlights feature is disabled in modded dimensions
