### ISSUE TITLE
waystone sync not working

### ISSUE THREAD

**Issue by charlie2209** [rfresh2/XaeroPlus#79]
i have been playing on a multiplayer server that has the xaero mods and the waystones mod, but the waystone sync option stopped working for everyone in the server after the server modpack was updated. the setting is enabled in the server config and everyone's player config, so i am not sure what the problem could be. so far i have tried toggling the config settings, restarting the server, and breaking and replacing waystones, but nothing has solved my issue. this may be a very small issue, but it is annoying to me and others so i would like some help if possible.

**Comment by rfresh2** [comment]
If you're playing on BetterMC, they requested I add a setting to put Waystone waypoints into a separate Xaero waypoint set. So that's probably what is confusing you.

Here's a video showing how to toggle it, or how to select which waypoint set to view: https://youtu.be/ZkSY14gXrOQ 
If you toggle this setting you might need to relog for the waystones to sync again

There's also a setting in Xaero's mods to render all waypoint sets in the world if you want to keep the waystone waypoints in their set but still have them be visible: Minimap Settings -> Waypoint Settings -> Render All Waypoint Sets

**Comment by charlie2209** [comment]
thank you for the fast reply but the video you sent says it's private. are you talking about the waystone waypoint set option in the xaeroplus settings? enabling that setting hasn't worked for me even after relogging.

**Comment by rfresh2** [comment]
the video should be published now

if its still not working or clear, please send me your `latest.log` when logging into the server where waystones should sync. you can upload it here: https://mclo.gs/

**Comment by charlie2209** [comment]
i tried that setting again to be sure, but it didn't work again. here is my log: https://mclo.gs/D1Qpkfr

**Comment by rfresh2** [comment]
If you select a different Sub-World/Dimension like this are the waypoints there? https://youtu.be/YMGMTrTkHcI

**Comment by charlie2209** [comment]
no they are not there

**Comment by rfresh2** [comment]
hmm that's weird.

I just installed a clean BMC4 server and client and verified they are syncing and they are in that other sub-world you can select.

If you have the `Waystone Waypoint Set` setting enabled you'd also have to switch the waypoint set you're looking at.

**Comment by charlie2209** [comment]
okay so your solution did work, but for whatever reason it just took about 20 minutes of me playing for the waypoints to actually appear on the waystones. thanks so much for your help!

**Comment by rfresh2** [comment]
I'm going to keep this open because I think waypoints should go into the existing worlds when possible. 

Not very user friendly to have to change that non-obvious setting every time you log in.

Will include that in the next update

**Comment by rfresh2** [comment]
@charlie2209 

Waypoints being created in different subworlds should be fixed in the latest release now
