### ISSUE TITLE
添加语言支持和功能询问

### ISSUE THREAD

**Issue by Adogs1** [rfresh2/XaeroPlus#80]
Xaero's World Map in It seems that synchronous exploration progress is not shared on the server. Can XaeroPlus support it.
and Can Chinese language be supported?

**Comment by Adogs1** [comment]
> Xaero的世界地图似乎没有在服务器上共享同步探索进度。XaeroPlus能支持吗？以及可以支持中文吗？

我使用最新版在原版配置按键界面显示的还是英文

**Comment by rfresh2** [comment]
1. I have no intent to add any server side features. You're suggestions are better directed to [Xaero who creates the base mods](https://legacy.curseforge.com/minecraft/mc-mods/xaeros-world-map/). If you want a shared map managed by the server, consider other software like Dynmap. 
2. XaeroPlus [already includes zh_cn translations](https://github.com/rfresh2/XaeroPlus/tree/fabric-1.20.1/src/main/resources/assets/xaeroplus/lang), not sure if you're talking about a different lang. You're welcome to PR corrections or translations for other langs though.

**Comment by Adogs1** [comment]
> 1. 我无意添加任何服务器端功能。您的建议最好直接针对[创建基本模组的 Xaero](https://legacy.curseforge.com/minecraft/mc-mods/xaeros-world-map/)。如果您想要由服务器管理的共享地图，请考虑使用其他软件，例如 Dynmap。
> 2. XaeroPlus [已经包含zh_cn翻译](https://githubfast.com/rfresh2/XaeroPlus/tree/fabric-1.20.1/src/main/resources/assets/xaeroplus/lang)，不确定你是否在谈论不同的语言。不过，欢迎您进行 PR 更正或翻译其他语言。

I come from China, and in our country, website access from other countries is restricted, so I cannot contact the author of xaeros world map to make this suggestion. At the same time, I have learned about the zh_cn of XaeroPlus translation, but I don't know how to use it.

**Comment by rfresh2** [comment]
If you change the language used by MC it changes it for all mods.

![firefox_hawtfXrBVl](https://github.com/rfresh2/XaeroPlus/assets/89827146/31af039a-e770-4f3e-94b1-0a5bd8706fd2)

Change it to this:

![java_NuBG2I812E](https://github.com/rfresh2/XaeroPlus/assets/89827146/70f46006-adee-4241-8042-1a7f2f766202)

XaeroPlus may have (mostly) complete translations for things I add, but that doesn't mean Xaero's WorldMap and Minimap do. I don't own those mods so I can't help you with that.

There are some projects run by other players to create translations for mods as resource packs you can load in Minecraft separately - without you needing any contact with the mod owners. https://github.com/CFPAOrg/Minecraft-Mod-Language-Package

**Comment by Adogs1** [comment]
Thanks！

**Comment by Adogs1** [comment]
> 如果您更改 MC 使用的语言，它会更改所有模组的语言。
> 
> ![firefox_hawtfXrBVl](https://usercontent.githubfast.com/user-images/89827146/281620266-31af039a-e770-4f3e-94b1-0a5bd8706fd2.png)
> 
> 把它改成这样：
> 
> ![java_NuBG2I812E](https://usercontent.githubfast.com/user-images/89827146/281620529-70f46006-adee-4241-8042-1a7f2f766202.png)
> 
> XaeroPlus 可能（大部分）为我添加的内容提供了完整的翻译，但这并不意味着 Xaero 的 WorldMap 和 Minimap 有。我不拥有这些模组，所以我帮不了你。
> 
> 其他玩家运行了一些项目来为模组创建翻译，作为资源包，您可以单独加载到 Minecraft 中 - 无需与模组所有者进行任何联系。https://githubfast.com/CFPAOrg/Minecraft-Mod-Language-Package

我试了一下，发现它并没有用
![Uploading QQ截图20231109233826.png…]()

**Comment by Adogs1** [comment]
> 如果您更改 MC 使用的语言，它会更改所有模组的语言。
> 
> ![firefox_hawtfXrBVl](https://usercontent.githubfast.com/user-images/89827146/281620266-31af039a-e770-4f3e-94b1-0a5bd8706fd2.png)
> 
> 把它改成这样：
> 
> ![java_NuBG2I812E](https://usercontent.githubfast.com/user-images/89827146/281620529-70f46006-adee-4241-8042-1a7f2f766202.png)
> 
> XaeroPlus 可能（大部分）为我添加的内容提供了完整的翻译，但这并不意味着 Xaero 的 WorldMap 和 Minimap 有。我不拥有这些模组，所以我帮不了你。
> 
> 其他玩家运行了一些项目来为模组创建翻译，作为资源包，您可以单独加载到 Minecraft 中 - 无需与模组所有者进行任何联系。https://githubfast.com/CFPAOrg/Minecraft-Mod-Language-Package

我试了一下，发现它并没有用
![QQ截图20231109233826](https://github.com/rfresh2/XaeroPlus/assets/111733210/252e0e6e-42c5-4dfb-bb68-10658009e04c)

**Comment by rfresh2** [comment]
Keybind settings not using translations will be fixed in the next update

**Comment by Adogs1** [comment]
> 不使用翻译的键绑定设置将在下次更新中修复

So should the update be fast？

**Comment by rfresh2** [comment]
updated releases are published now

**Comment by Adogs1** [comment]
> updated releases are published now

Thanks!!!
