### ISSUE TITLE
XaeroPlust crash on Minecraft 1.20.4 with Waystones installed

### ISSUE THREAD

**Issue by ghost** [rfresh2/XaeroPlus#99]
# Mod runtime information
- **Minecraft version**: 1.20.4
- **Loader**: Fabric 0.15.3
- **Mod version**: 1.20.4
- **Xaero's Minimap version**: 23.9.6
- **Xaero's World Map version**: 1.37.6

## Other
- **Waystones version**: 16.0.3
- **Balm version**: 9.0.4

Minecraft crash on launch with both `XaeroPlus` and `Waystones` installed, in the logs the following error is reported as the main cause of the crash:

```text
java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/blay09/mods/waystones/api/KnownWaystonesEvent
at xaero.map.WorldMap.tryLoadLater(WorldMap.java:262)
	at xaero.map.core.XaeroWorldMapCore.onMinecraftRunTick(XaeroWorldMapCore.java:169)
	at net.minecraft.class_310.handler$dlp000$xaeroworldmap$onRunTickStart(class_310.java:17275)
	at net.minecraft.class_310.method_1523(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at
...

Caused by: java.lang.ClassNotFoundException: net.blay09.mods.waystones.api.KnownWaystonesEvent
```

After browsing the [Waystones](https://github.com/TwelveIterationMods/Waystones) source code I found that
the commit [4c212741d9f3079d9dec660eec66baa4bc070082](https://github.com/TwelveIterationMods/Waystones/commit/4c212741d9f3079d9dec660eec66baa4bc070082) causes the crash because the class `KnownWaystonesEvent` is removed from the code, so in new Waystones updates is not available and the `XaeroPlus` mod crashes when a new version of `Waystones` is installed.

NOTE: After some testing I managed to resolve the issue by updating some parts of the code, I was thinking on doing a PR but not sure...

**Comment by rfresh2** [comment]
Thanks for reporting, seems there was a waystones update a week or 2 ago that changed some internals when it was updated to 1.20.4.

i'll release an update shortly

**Comment by rfresh2** [comment]
Released https://github.com/rfresh2/XaeroPlus/releases/tag/Fabric-1.20.4-8
